package model

// attribute: controllerServiceReferencingComponentsEntity
type ControllerServiceReferencingComponentsEntity struct {
	ControllerServiceReferencingComponents []ControllerServiceReferencingComponentEntity `json:"controllerServiceReferencingComponents"`
}
