package model

type ControllerServiceReferencingComponentsEntity struct {
	ControllerServiceReferencingComponents []ControllerServiceReferencingComponentEntity `json:"controllerServiceReferencingComponents"`
}
