package model

type Snippet struct {
	Id                  string        `json:"id"`                  // The id of the snippet.
	Uri                 string        `json:"uri"`                 // The URI of the snippet.
	ParentGroupId       string        `json:"parentGroupId"`       // The group id for the components in the snippet.
	Linked              bool          `json:"linked"`              // Whether or not the snippet is linked to the underlying data flow. For instance if linked was set to true and the snippet was deleted it would also deleted the components in the snippet. If the snippet was not linked, deleting the snippet would only remove the snippet and leave the component intact.
	ProcessGroups       []string      `json:"processGroups"`       // The ids of the process groups in this snippet. These ids will be populated within each response. They can be specified when creating a snippet. However, once a snippet has been created its contents cannot be modified (these ids are ignored during update requests).
	RemoteProcessGroups []string      `json:"remoteProcessGroups"` // The ids of the remote process groups in this snippet. These ids will be populated within each response. They can be specified when creating a snippet. However, once a snippet has been created its contents cannot be modified (these ids are ignored during update requests).
	Processors          []string      `json:"processors"`          // The ids of the processors in this snippet. These ids will be populated within each response. They can be specified when creating a snippet. However, once a snippet has been created its contents cannot be modified (these ids are ignored during update requests).
	InputPorts          []string      `json:"inputPorts"`          // The ids of the input ports in this snippet. These ids will be populated within each response. They can be specified when creating a snippet. However, once a snippet has been created its contents cannot be modified (these ids are ignored during update requests).
	OutputPorts         []string      `json:"outputPorts"`         // The ids of the output ports in this snippet. These ids will be populated within each response. They can be specified when creating a snippet. However, once a snippet has been created its contents cannot be modified (these ids are ignored during update requests).
	Connections         []string      `json:"connections"`         // The ids of the connections in this snippet. These ids will be populated within each response. They can be specified when creating a snippet. However, once a snippet has been created its contents cannot be modified (these ids are ignored during update requests).
	Labels              []string      `json:"labels"`              // The ids of the labels in this snippet. These ids will be populated within each response. They can be specified when creating a snippet. However, once a snippet has been created its contents cannot be modified (these ids are ignored during update requests).
	Funnels             []string      `json:"funnels"`             // The ids of the funnels in this snippet. These ids will be populated within each response. They can be specified when creating a snippet. However, once a snippet has been created its contents cannot be modified (these ids are ignored during update requests).
	Contents            []FlowSnippet `json:"contents"`            // The contents of the configuration for the snippet.
}
